# fly.toml app configuration file generated for homework-snowy-water-238 on 2025-06-17T20:51:22+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homework-snowy-water-238'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
